### PR TITLE
day1 project created 

### PR DESCRIPTION
**Pull request by Nes09**

### CODE REVIEW

**Comment by Nes09** [comment]
Marina, please review my code

**Comment by Marat311** [comment]
Elena, can you add String school name?

**Review by Marat311 — APPROVED** [review]

**Comment by Marat311** [comment]
yes you can merge it

**Comment by Nes09** [comment]
can you merge it?

**Comment by Nes09** [comment]
ok

**Comment by Nes09** [comment]
Marina, let's merge 2 comments

**Review by Marat311 — COMMENTED** [review]
i dont see your code

**Comment by Marat311** [comment]
can you add one more comment

**Pull request merged**
